apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sydi47lqi-nodejs 
  janus-idp.io/tekton: sydi47lqi-nodejs
  backstage.io/kubernetes-id: sydi47lqi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sydi47lqi-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  