apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sydi47lqi-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e15437cc253c70a5ec6c205ac5671cf18363f423@sha256:b40632260e3e607d9bf8324c52fb2908a27aa61e0c1f24c6db4ca0dfc0044be4
          name: container-image
